properties:
  apiVersion:
    default: prometheusservice.services.k8s.aws/v1alpha1
    description: APIVersion for the resource
    type: string
  config:
    description: WorkspaceSpec defines the desired state of Workspace.
    properties:
      alias:
        description: An optional user-assigned alias for this workspace. This alias is for user reference and does not need to be unique.
        type: string
      tags:
        additionalProperties:
          type: string
        description: Optional, user-provided tags for this workspace.
        type: object
    title: prometheusservice.services.k8s.aws.Workspace configuration options
    type: object
  kind:
    default: Workspace
    description: Kind for the resource
    type: string
  namespace:
    description: Namespace for the resource
    namespace: default
    type: string
  resources:
    enum:
      - prometheusservice.services.k8s.aws.workspace
