properties:
  apiVersion:
    default: prometheusservice.services.k8s.aws/v1alpha1
    description: APIVersion for the resource
    type: string
  config:
    description: RuleGroupsNamespaceSpec defines the desired state of RuleGroupsNamespace.
    properties:
      configuration:
        type: string
      name:
        description: The rule groups namespace name.
        type: string
      tags:
        additionalProperties:
          type: string
        description: Optional, user-provided tags for this rule groups namespace.
        type: object
      workspaceID:
        description: The ID of the workspace in which to create the rule group namespace.
        type: string
      workspaceRef:
        description: "AWSResourceReferenceWrapper provides a wrapper around *AWSResourceReference type to provide more user friendly syntax for references using 'from' field Ex: APIIDRef: \n from: name: my-api"
        properties:
          from:
            description: AWSResourceReference provides all the values necessary to reference another k8s resource for finding the identifier(Id/ARN/Name)
            properties:
              name:
                type: string
            type: object
        type: object
    required:
      - configuration
      - name
    title: prometheusservice.services.k8s.aws.RuleGroupsNamespace configuration options
    type: object
  kind:
    default: RuleGroupsNamespace
    description: Kind for the resource
    type: string
  namespace:
    description: Namespace for the resource
    namespace: default
    type: string
  resources:
    enum:
      - prometheusservice.services.k8s.aws.rulegroupsnamespace
