properties:
  apiVersion:
    default: sagemaker.services.k8s.aws/v1alpha1
    description: APIVersion for the resource
    type: string
  config:
    description: NotebookInstanceLifecycleConfigSpec defines the desired state of NotebookInstanceLifecycleConfig.
    properties:
      notebookInstanceLifecycleConfigName:
        description: The name of the lifecycle configuration.
        type: string
      onCreate:
        description: A shell script that runs only once, when you create a notebook instance. The shell script must be a base64-encoded string.
        items:
          description: "Contains the notebook instance lifecycle configuration script. \n Each lifecycle configuration script has a limit of 16384 characters. \n The value of the $PATH environment variable that is available to both scripts is /sbin:bin:/usr/sbin:/usr/bin. \n View CloudWatch Logs for notebook instance lifecycle configurations in log group /aws/sagemaker/NotebookInstances in log stream [notebook-instance-name]/[LifecycleConfigHook]. \n Lifecycle configuration scripts cannot run for longer than 5 minutes. If a script runs for longer than 5 minutes, it fails and the notebook instance is not created or started. \n For information about notebook instance lifestyle configurations, see Step 2.1: (Optional) Customize a Notebook Instance (https://docs.aws.amazon.com/sagemaker/latest/dg/notebook-lifecycle-config.html)."
          properties:
            content:
              type: string
          type: object
        type: array
      onStart:
        description: A shell script that runs every time you start a notebook instance, including when you create the notebook instance. The shell script must be a base64-encoded string.
        items:
          description: "Contains the notebook instance lifecycle configuration script. \n Each lifecycle configuration script has a limit of 16384 characters. \n The value of the $PATH environment variable that is available to both scripts is /sbin:bin:/usr/sbin:/usr/bin. \n View CloudWatch Logs for notebook instance lifecycle configurations in log group /aws/sagemaker/NotebookInstances in log stream [notebook-instance-name]/[LifecycleConfigHook]. \n Lifecycle configuration scripts cannot run for longer than 5 minutes. If a script runs for longer than 5 minutes, it fails and the notebook instance is not created or started. \n For information about notebook instance lifestyle configurations, see Step 2.1: (Optional) Customize a Notebook Instance (https://docs.aws.amazon.com/sagemaker/latest/dg/notebook-lifecycle-config.html)."
          properties:
            content:
              type: string
          type: object
        type: array
    required:
      - notebookInstanceLifecycleConfigName
    title: sagemaker.services.k8s.aws.NotebookInstanceLifecycleConfig configuration options
    type: object
  kind:
    default: NotebookInstanceLifecycleConfig
    description: Kind for the resource
    type: string
  namespace:
    description: Namespace for the resource
    namespace: default
    type: string
  resources:
    enum:
      - sagemaker.services.k8s.aws.notebookinstancelifecycleconfig
