properties:
  apiVersion:
    default: sagemaker.services.k8s.aws/v1alpha1
    description: APIVersion for the resource
    type: string
  config:
    description: EndpointConfigSpec defines the desired state of EndpointConfig.
    properties:
      asyncInferenceConfig:
        description: Specifies configuration for how an endpoint performs asynchronous inference. This is a required field in order for your Endpoint to be invoked using InvokeEndpointAsync (https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_runtime_InvokeEndpointAsync.html).
        properties:
          clientConfig:
            description: Configures the behavior of the client used by SageMaker to interact with the model container during asynchronous inference.
            properties:
              maxConcurrentInvocationsPerInstance:
                format: int64
                type: integer
            type: object
          outputConfig:
            description: Specifies the configuration for asynchronous inference invocation outputs.
            properties:
              kmsKeyID:
                type: string
              notificationConfig:
                description: Specifies the configuration for notifications of inference results for asynchronous inference.
                properties:
                  errorTopic:
                    type: string
                  successTopic:
                    type: string
                type: object
              s3OutputPath:
                type: string
            type: object
        type: object
      dataCaptureConfig:
        description: Configuration to control how SageMaker captures inference data.
        properties:
          captureContentTypeHeader:
            description: Configuration specifying how to treat different headers. If no headers are specified SageMaker will by default base64 encode when capturing the data.
            properties:
              csvContentTypes:
                items:
                  type: string
                type: array
              jsonContentTypes:
                items:
                  type: string
                type: array
            type: object
          captureOptions:
            items:
              description: Specifies data Model Monitor will capture.
              properties:
                captureMode:
                  type: string
              type: object
            type: array
          destinationS3URI:
            type: string
          enableCapture:
            type: boolean
          initialSamplingPercentage:
            format: int64
            type: integer
          kmsKeyID:
            type: string
        type: object
      endpointConfigName:
        description: The name of the endpoint configuration. You specify this name in a CreateEndpoint request.
        type: string
      kmsKeyID:
        description: "The Amazon Resource Name (ARN) of a Amazon Web Services Key Management Service key that SageMaker uses to encrypt data on the storage volume attached to the ML compute instance that hosts the endpoint. \n The KmsKeyId can be any of the following formats: \n * Key ID: 1234abcd-12ab-34cd-56ef-1234567890ab \n * Key ARN: arn:aws:kms:us-west-2:111122223333:key/1234abcd-12ab-34cd-56ef-1234567890ab \n * Alias name: alias/ExampleAlias \n * Alias name ARN: arn:aws:kms:us-west-2:111122223333:alias/ExampleAlias \n The KMS key policy must grant permission to the IAM role that you specify in your CreateEndpoint, UpdateEndpoint requests. For more information, refer to the Amazon Web Services Key Management Service section Using Key Policies in Amazon Web Services KMS (https://docs.aws.amazon.com/kms/latest/developerguide/key-policies.html) \n Certain Nitro-based instances include local storage, dependent on the instance type. Local storage volumes are encrypted using a hardware module on the instance. You can't request a KmsKeyId when using an instance type with local storage. If any of the models that you specify in the ProductionVariants parameter use nitro-based instances with local storage, do not specify a value for the KmsKeyId parameter. If you specify a value for KmsKeyId when using any nitro-based instances with local storage, the call to CreateEndpointConfig fails. \n For a list of instance types that support local instance storage, see Instance Store Volumes (https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/InstanceStorage.html#instance-store-volumes). \n For more information about local instance storage encryption, see SSD Instance Store Volumes (https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ssd-instance-store.html)."
        type: string
      productionVariants:
        description: An array of ProductionVariant objects, one for each model that you want to host at this endpoint.
        items:
          description: Identifies a model that you want to host and the resources chosen to deploy for hosting it. If you are deploying multiple models, tell SageMaker how to distribute traffic among the models by specifying variant weights. For more information on production variants, check Production variants (https://docs.aws.amazon.com/sagemaker/latest/dg/model-ab-testing.html).
          properties:
            acceleratorType:
              type: string
            containerStartupHealthCheckTimeoutInSeconds:
              format: int64
              type: integer
            coreDumpConfig:
              description: Specifies configuration for a core dump from the model container when the process crashes.
              properties:
                destinationS3URI:
                  type: string
                kmsKeyID:
                  type: string
              type: object
            enableSSMAccess:
              type: boolean
            initialInstanceCount:
              format: int64
              type: integer
            initialVariantWeight:
              type: number
            instanceType:
              type: string
            modelDataDownloadTimeoutInSeconds:
              format: int64
              type: integer
            modelName:
              type: string
            serverlessConfig:
              description: Specifies the serverless configuration for an endpoint variant.
              properties:
                maxConcurrency:
                  format: int64
                  type: integer
                memorySizeInMB:
                  format: int64
                  type: integer
              type: object
            variantName:
              type: string
            volumeSizeInGB:
              format: int64
              type: integer
          type: object
        type: array
      tags:
        description: An array of key-value pairs. You can use tags to categorize your Amazon Web Services resources in different ways, for example, by purpose, owner, or environment. For more information, see Tagging Amazon Web Services Resources (https://docs.aws.amazon.com/general/latest/gr/aws_tagging.html).
        items:
          description: "A tag object that consists of a key and an optional value, used to manage metadata for SageMaker Amazon Web Services resources. \n You can add tags to notebook instances, training jobs, hyperparameter tuning jobs, batch transform jobs, models, labeling jobs, work teams, endpoint configurations, and endpoints. For more information on adding tags to SageMaker resources, see AddTags. \n For more information on adding metadata to your Amazon Web Services resources with tagging, see Tagging Amazon Web Services resources (https://docs.aws.amazon.com/general/latest/gr/aws_tagging.html). For advice on best practices for managing Amazon Web Services resources with tagging, see Tagging Best Practices: Implement an Effective Amazon Web Services Resource Tagging Strategy (https://d1.awsstatic.com/whitepapers/aws-tagging-best-practices.pdf)."
          properties:
            key:
              type: string
            value:
              type: string
          type: object
        type: array
    required:
      - endpointConfigName
      - productionVariants
    title: sagemaker.services.k8s.aws.EndpointConfig configuration options
    type: object
  kind:
    default: EndpointConfig
    description: Kind for the resource
    type: string
  namespace:
    description: Namespace for the resource
    namespace: default
    type: string
  resources:
    enum:
      - sagemaker.services.k8s.aws.endpointconfig
