properties:
  apiVersion:
    default: sns.services.k8s.aws/v1alpha1
    description: APIVersion for the resource
    type: string
  config:
    description: "PlatformApplicationSpec defines the desired state of PlatformApplication. \n Platform application object."
    properties:
      eventDeliveryFailure:
        type: string
      eventEndpointCreated:
        type: string
      eventEndpointCreatedRef:
        description: "AWSResourceReferenceWrapper provides a wrapper around *AWSResourceReference type to provide more user friendly syntax for references using 'from' field Ex: APIIDRef: \n from: name: my-api"
        properties:
          from:
            description: AWSResourceReference provides all the values necessary to reference another k8s resource for finding the identifier(Id/ARN/Name)
            properties:
              name:
                type: string
            type: object
        type: object
      eventEndpointDeleted:
        type: string
      eventEndpointDeletedRef:
        description: "AWSResourceReferenceWrapper provides a wrapper around *AWSResourceReference type to provide more user friendly syntax for references using 'from' field Ex: APIIDRef: \n from: name: my-api"
        properties:
          from:
            description: AWSResourceReference provides all the values necessary to reference another k8s resource for finding the identifier(Id/ARN/Name)
            properties:
              name:
                type: string
            type: object
        type: object
      eventEndpointUpdated:
        type: string
      eventEndpointUpdatedRef:
        description: "AWSResourceReferenceWrapper provides a wrapper around *AWSResourceReference type to provide more user friendly syntax for references using 'from' field Ex: APIIDRef: \n from: name: my-api"
        properties:
          from:
            description: AWSResourceReference provides all the values necessary to reference another k8s resource for finding the identifier(Id/ARN/Name)
            properties:
              name:
                type: string
            type: object
        type: object
      failureFeedbackRoleARN:
        type: string
      failureFeedbackRoleRef:
        description: "AWSResourceReferenceWrapper provides a wrapper around *AWSResourceReference type to provide more user friendly syntax for references using 'from' field Ex: APIIDRef: \n from: name: my-api"
        properties:
          from:
            description: AWSResourceReference provides all the values necessary to reference another k8s resource for finding the identifier(Id/ARN/Name)
            properties:
              name:
                type: string
            type: object
        type: object
      name:
        description: Application names must be made up of only uppercase and lowercase ASCII letters, numbers, underscores, hyphens, and periods, and must be between 1 and 256 characters long.
        type: string
      platform:
        description: 'The following platforms are supported: ADM (Amazon Device Messaging), APNS (Apple Push Notification Service), APNS_SANDBOX, and GCM (Firebase Cloud Messaging).'
        type: string
      platformCredential:
        type: string
      platformPrincipal:
        type: string
      successFeedbackRoleARN:
        type: string
      successFeedbackRoleRef:
        description: "AWSResourceReferenceWrapper provides a wrapper around *AWSResourceReference type to provide more user friendly syntax for references using 'from' field Ex: APIIDRef: \n from: name: my-api"
        properties:
          from:
            description: AWSResourceReference provides all the values necessary to reference another k8s resource for finding the identifier(Id/ARN/Name)
            properties:
              name:
                type: string
            type: object
        type: object
      successFeedbackSampleRate:
        type: string
    required:
      - name
      - platform
    title: sns.services.k8s.aws.PlatformApplication configuration options
    type: object
  kind:
    default: PlatformApplication
    description: Kind for the resource
    type: string
  namespace:
    description: Namespace for the resource
    namespace: default
    type: string
  resources:
    enum:
      - sns.services.k8s.aws.platformapplication
